[tool.poetry]
name = "minibot"
version = "0.0.1"
description = ""
authors = ["sonic182 <johander1822@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.15"
aiosonic = "^0.30.1"
llm-async = "^0.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
